# -*- coding: utf-8 -*-
"""Copy of Sales_Analytics_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exuji4A_TtJaAa2NXiD8M33Jjv_Tj5au
"""

# ===============================
# 1️⃣ INSTALL & IMPORT LIBRARIES
# ===============================
!pip install --upgrade gspread gspread-dataframe plotly seaborn

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import gspread
from gspread_dataframe import get_as_dataframe
from google.colab import auth
from google.auth import default
# Install necessary packages
!pip install --upgrade gspread gspread-dataframe google-auth-oauthlib





# Authenticate user in Colab
auth.authenticate_user()

# Get credentials from Colab
creds, _ = default()

# Connect gspread client
gc = gspread.authorize(creds)

# Replace with your Google Sheet URL
sheet_url = "https://docs.google.com/spreadsheets/d/1E-r-5RQSWYt1hKc_7WUlGVtbAGh8AAIisb2sbWBNTpk/edit?usp=sharing"
sh = gc.open_by_url(sheet_url)
worksheet = sh.sheet1  # first sheet

# Load data into pandas
df = get_as_dataframe(worksheet)
df = df.dropna(how='all')
df.head()


# sns.set(style="whitegrid")

# # ===============================
# # 2️⃣ AUTHENTICATE & CONNECT TO GOOGLE SHEETS
# # ===============================
# auth.authenticate_user()  # Google Colab authentication
# gc = gspread.authorize(gspread.auth.default())

# # Replace with your Google Sheet link (base URL without /edit)
# sheet_url = "https://docs.google.com/spreadsheets/d/1E-r-5RQSWYt1hKc_7WUlGVtbAGh8AAIisb2sbWBNTpk"
# sh = gc.open_by_url(sheet_url)
# worksheet = sh.sheet1  # first worksheet

# # Load data into pandas DataFrame
# df = get_as_dataframe(worksheet)
# df = df.dropna(how='all')  # remove empty rows

# ===============================
# 3️⃣ CLEAN DATA
# ===============================
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.drop_duplicates(inplace=True)

# Convert order_date to datetime
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df = df.dropna(subset=['order_date'])

# Add additional columns
df['month'] = df['order_date'].dt.month_name()
df['year'] = df['order_date'].dt.year
df['day'] = df['order_date'].dt.day
df['discount_pct'] = df['discount'] * 100

# ===============================
# 4️⃣ BASIC METRICS
# ===============================
total_revenue = df['sales'].sum()
average_sale = df['sales'].mean()
print("💰 Total Revenue:", round(total_revenue,2))
print("📊 Average Sale per Invoice:", round(average_sale,2))

# ===============================
# 5️⃣ GROUPED DATA FOR CHARTS
# ===============================
city_sales = df.groupby('city')['sales'].sum().sort_values(ascending=False)
region_sales = df.groupby('region')['sales'].sum().sort_values(ascending=False)
category_sales = df.groupby('category')['sales'].sum().sort_values(ascending=False)
subcat_sales = df.groupby('sub_category')['sales'].sum().sort_values(ascending=False)
monthly_sales = df.groupby('order_date')['sales'].sum().sort_values(ascending=False)

# ===============================
# 6️⃣ PLOT INTERACTIVE DASHBOARD
# ===============================
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=("Revenue by City", "Revenue by Region", "Monthly Sales Trend", "Revenue by Category")
)

# Revenue by City
fig.add_trace(go.Bar(x=city_sales.index, y=city_sales.values, name="City"), row=1, col=1)

# Revenue by Region
fig.add_trace(go.Bar(x=region_sales.index, y=region_sales.values, name="Region"), row=1, col=2)

# Monthly Sales Trend
fig.add_trace(go.Scatter(x=monthly_sales.index, y=monthly_sales.values, mode='lines+markers', name="Monthly Trend"), row=2, col=1)

# Revenue by Category
fig.add_trace(go.Bar(x=category_sales.index, y=category_sales.values, name="Category"), row=2, col=2)

# Layout settings
fig.update_layout(height=800, width=1000, title_text="Supermarket Sales Dashboard")
fig.show()

# Optional: Save as HTML
fig.write_html("supermarket_sales_dashboard.html")

# ===============================
# 7️⃣ ADDITIONAL CHARTS
# ===============================

# Discount vs Profit by Category
fig2 = px.scatter(df, x='discount_pct', y='profit',
                 color='category',
                 size='sales',
                 hover_data=['customer_name','city'],
                 title='Discount vs Profit by Category')
fig2.show()

# Revenue by Sub-Category
fig3 = px.bar(subcat_sales.reset_index(),
             x='sub_category', y='sales',
             title='Revenue by Sub-Category',
             labels={'sales':'Revenue','sub_category':'Sub-Category'},
             color='sales',
             color_continuous_scale='Plotly3')
fig3.show()



from google.colab import drive
drive.mount('/content/drive')